/**
 * ~1,000 liquid names for the 70%+ next-month riser search.
 * Listed watchlist is always included first by the scanner.
 */
const RAW = `
AAPL MSFT NVDA GOOG GOOGL AMZN META AVGO TSLA SPCX BRK-B JPM V MA UNH XOM CVX LLY JNJ ABBV MRK PFE COST WMT HD PG KO PEP MCD NKE SBUX DIS NFLX CMCSA T VZ
BAC WFC GS MS C AXP BLK SCHW SPGI BX AMD ORCL CRM ADBE CSCO INTC QCOM TXN AMAT LRCX KLAC MU SNPS CDNS NOW PANW CRWD FTNT SNOW PLTR UBER ABNB SHOP SQ PYPL IBM ACN INTU ADP
ISRG TMO DHR SYK BSX MDT TSM ASML ARM SMCI AMKR ON MRVL ADI NXPI BA CAT DE GE HON UNP UPS FDX RTX LMT NOC GD MMM EMR ETN PH
RCL CCL DAL UAL AAL MAR HLT BKNG CMG YUM TJX LOW TGT COP SLB EOG MPC PSX OXY FCX NEM LIN APD NEE DUK SO AEP AMT PLD EQIX SPG
SPY QQQ IWM DIA VTI VOO SMH SOXX XLF XLE XLK XLV XLI XLY XLP XLU XLB XLRE XBI IBB ARKK BOTZ ROBO GLD IAU SLV PLTM GDX TLT IEF HYG LQD
AMGN GILD BMY VRTX REGN ZTS CI ELV HUM HCA CVS BDX EW IDXX DXCM ALNY GEHC IQV COR MCK CAH A WAT MTD APP DELL HPE HPQ NTAP STX WDC ANET MSI KEYS TEL GLW
MPWR MCHP SWKS TER ENTG FSLR ENPH COIN HOOD SOFI NET DDOG TEAM WDAY ZS OKTA MDB HUBS TWLO ZM RBLX EA TTWO SPOT DASH LYFT XYZ USB PNC TFC COF MET PRU AFL ALL PGR TRV CB AIG MMC AON AJG ICE CME NDAQ MSCI MCO TROW BK STT FITB
KEY RF HBAN CFG KKR APO ARES ITW ROK IR CARR OTIS TT JCI CMI PCAR URI GWW FAST CTAS VRSK CSX NSC WM RSG LHX TDG AXON HWM VRT PWR
PM MO CL KMB GIS MDLZ HSY KR SYY ADM STZ EL ULTA LULU DECK ORLY AZO ROST BURL DG DLTR DHI LEN PHM F GM RIVN DPZ WING
WMB KMI OKE LNG DVN FANG HAL BKR VLO HES EQT DOW DD ALB NUE STLD VMC MLM CTVA WELL O CCI DLR PSA EXR AVB EQR VICI WY SRE D EXC XEL PEG ED PCG AWK
SAP NVO AZN GSK SONY TM UL BTI RIO BHP VALE PDD BABA MELI SE NU IBN HDB INFY NVS SNY HSBC RY TD IWF IWD IJH IJR VB VO VUG VTV QQQM XOP KRE ITB XHB XME GDXJ PPLT SIVR USO TAN ICLN CIBR SKYY IGV IYW EEM EFA VEA VWO FXI KWEB EWJ EWZ INDA MCHI ARKW ARKG HACK
ABT ABT-SKIP KVUE MDT-DUP BIIB MRNA ILMN HOLX ALGN PODD RMD STE ZBH CNC MOH DGX LH RVTY TECH BIO WST CRL
FI FIS PAYX GPN CPAY ADSK CTSH IT EPAM LDOS BR IBM-DUP HP ANSS PTC CDW AKAM FFIV GEN NTNX ESTC PATH S CRM-DUP
CHTR TMUS LUMN FYBR TTD ROKU FOXA FOX NWSA PARA WBD LYV MTCH PINS SNAP RBLX-DUP
FICO CDNS-DUP SNPS-DUP KLAC-DUP LRCX-DUP AMAT-DUP
SHW ECL PPG APD-DUP LIN-DUP NEM-DUP FCX-DUP NUE-DUP STLD-DUP RS CF MOS ADM-DUP BG CTVA-DUP DOW-DUP DD-DUP EMN ALB-DUP IFF LYB VMC-DUP MLM-DUP PKG AVY IP WRK SEE AMCR GPK
GEV TT-DUP ETN-DUP EMR-DUP ROK-DUP PH-DUP ITW-DUP IR-DUP CARR-DUP OTIS-DUP JCI-DUP CMI-DUP PCAR-DUP URI-DUP GWW-DUP FAST-DUP CTAS-DUP VRSK-DUP CSX-DUP NSC-DUP UNP-DUP UPS-DUP FDX-DUP WM-DUP RSG-DUP LHX-DUP TDG-DUP AXON-DUP HWM-DUP VRT-DUP PWR-DUP BA-DUP CAT-DUP DE-DUP HON-DUP RTX-DUP LMT-DUP NOC-DUP GD-DUP MMM-DUP GE-DUP
LII BLDR J MAS OC PHM-DUP DHI-DUP LEN-DUP NVR TOL MHK FBHS WHR SWK SNA PNR IEX ROP AME DOV XYL PNR-DUP FTV TDY TXT HII HII-DUP
AOS GNRC SWK-DUP
CHD CLX KDP MNST K CELH HSY-DUP MDLZ-DUP GIS-DUP KMB-DUP CL-DUP PG-DUP KO-DUP PEP-DUP COST-DUP WMT-DUP TGT-DUP KR-DUP SYY-DUP ADM-DUP STZ-DUP EL-DUP ULTA-DUP LULU-DUP DECK-DUP ORLY-DUP AZO-DUP ROST-DUP BURL-DUP DG-DUP DLTR-DUP
TSCO POOL BBY GRMN HAS MAT NKE-DUP SBUX-DUP MCD-DUP YUM-DUP CMG-DUP DPZ-DUP WING-DUP DASH-DUP SBUX
RCL-DUP CCL-DUP DAL-DUP UAL-DUP AAL-DUP LUV MAR-DUP HLT-DUP BKNG-DUP ABNB-DUP EXPE NCLH
GM-DUP F-DUP TSLA-DUP RIVN-DUP LCID
CVX-DUP XOM-DUP COP-DUP SLB-DUP EOG-DUP MPC-DUP PSX-DUP OXY-DUP DVN-DUP FANG-DUP HAL-DUP BKR-DUP VLO-DUP HES-DUP EQT-DUP WMB-DUP KMI-DUP OKE-DUP LNG-DUP TRGP CTRA OVV PR AR APA MRO CTRA-DUP
NEE-DUP DUK-DUP SO-DUP AEP-DUP SRE-DUP D-DUP EXC-DUP XEL-DUP PEG-DUP ED-DUP PCG-DUP AWK-DUP DTE EIX FE AEE CMS CNP ES ETR EVRG LNT NI PPL WEC AES VST CEG NRG PNW ATO
AMT-DUP PLD-DUP EQIX-DUP SPG-DUP WELL-DUP O-DUP CCI-DUP DLR-DUP PSA-DUP EXR-DUP AVB-DUP EQR-DUP VICI-DUP WY-DUP SPG IRM SBAC INVH MAA ESS UDR CPT KIM REG BXP HST PEAK ARE VTR DOC
JPM-DUP BAC-DUP WFC-DUP GS-DUP MS-DUP C-DUP AXP-DUP BLK-DUP SCHW-DUP SPGI-DUP BX-DUP USB-DUP PNC-DUP TFC-DUP COF-DUP MET-DUP PRU-DUP AFL-DUP ALL-DUP PGR-DUP TRV-DUP CB-DUP AIG-DUP MMC-DUP AON-DUP AJG-DUP ICE-DUP CME-DUP NDAQ-DUP MSCI-DUP MCO-DUP TROW-DUP BK-DUP STT-DUP FITB-DUP KEY-DUP RF-DUP HBAN-DUP CFG-DUP KKR-DUP APO-DUP ARES-DUP
BRO WRB CINF L FDS NTRS RJF AMP BEN IVZ MKTX TW DFS SYF ALLY HOOD-DUP SOFI-DUP COIN-DUP PYPL-DUP SQ-DUP V-DUP MA-DUP
UNH-DUP ELV-DUP CI-DUP HUM-DUP CNC MOH HCA-DUP CVS-DUP MCK-DUP CAH-DUP COR-DUP JNJ-DUP LLY-DUP ABBV-DUP MRK-DUP PFE-DUP AMGN-DUP GILD-DUP BMY-DUP VRTX-DUP REGN-DUP ZTS-DUP BDX-DUP SYK-DUP BSX-DUP MDT-DUP ISRG-DUP TMO-DUP DHR-DUP EW-DUP IDXX-DUP DXCM-DUP ALNY-DUP GEHC-DUP IQV-DUP A-DUP WAT-DUP MTD-DUP
ABT BDX HOLX BAX BAX-DUP ZBH RMD STE TFX PODD ALGN ILMN BIIB MRNA INCY EXEL SGEN BMRN NBIX UTHR VKTX SRPT
MSFT-DUP AAPL-DUP NVDA-DUP AVGO-DUP TSM-DUP ASML-DUP AMAT-DUP LRCX-DUP KLAC-DUP MU-DUP AMD-DUP INTC-DUP QCOM-DUP TXN-DUP ADI-DUP NXPI-DUP MRVL-DUP ARM-DUP SNPS-DUP CDNS-DUP NOW-DUP CRM-DUP ORCL-DUP ADBE-DUP INTU-DUP ACN-DUP IBM-DUP CSCO-DUP PANW-DUP CRWD-DUP FTNT-DUP ZS-DUP DDOG-DUP NET-DUP SNOW-DUP MDB-DUP TEAM-DUP WDAY-DUP OKTA-DUP HUBS-DUP TWLO-DUP ZM-DUP
PLTR-DUP APP-DUP DELL-DUP HPE-DUP HPQ-DUP NTAP-DUP STX-DUP WDC-DUP ANET-DUP MSI-DUP KEYS-DUP TEL-DUP GLW-DUP MPWR-DUP MCHP-DUP SWKS-DUP TER-DUP ENTG-DUP SMCI-DUP AMKR-DUP ON-DUP FSLR-DUP ENPH-DUP
META-DUP GOOG-DUP GOOGL-DUP AMZN-DUP NFLX-DUP DIS-DUP CMCSA-DUP T-DUP VZ-DUP TMUS CHTR
SHOP-DUP UBER-DUP ABNB-DUP SPOT-DUP RBLX-DUP EA-DUP TTWO-DUP
LLY-DUP
IWM QQQ SPY
ARKK ARKW ARKG ARKQ ARKF IBIT GBTC ETHE BITO
XLF XLE XLK XLV XLI XLY XLP XLU XLB XLRE XLC SMH SOXX SOXL USD TQQQ SQQQ SPXL UPRO TNA UWM QLD SSO
IWF IWD IJH IJR IWB IVE IVW RSP MOAT QUAL MTUM VLUE USMV SPHQ SPLG IVV VOO VTI VUG VTV VO VB VGT VFH VHT VIS VCR VDC VDE VAW VNQ VPU VIG VYM SCHD SCHG SCHV SCHX DGRO DGRW JEPI JEPQ QYLD XYLD RYLD DIV O USMV
EFA EEM VEA VWO VXUS IEFA IEMG VGK EWJ EWZ EWT EWY EWH EWS EWA EWC EWG EWI EWP EWU INDA MCHI FXI KWEB ASHR SCHE SPEM VYMI VYMI
GLD IAU SLV SIVR PPLT PLTM PALL GDX GDXJ SIL SILJ RING SGOL BAR AAAU OUNZ
TLT IEF SHY BND AGG BNDX LQD HYG JNK EMB MUB VCIT VCSH GOVT TIP SCHZ SPHY SJNK FLOT BIL SGOV SHV
USO BNO UNG DBA DBC PDBC GSG COPX REMX LIT TAN ICLN QCLN PBW FAN SMOG GRID CIBR HACK BUG SKYY CLOU WCLD IGV IYW BOTZ ROBO IRBO QTUM ARKQ
XOP OIH IEZ XME PICK XHB ITB KRE KBE IAI IYF IYG IYJ IYC IYK IHI IBB XBI ARKG GNOM IDNA
DIA MDY IJR IWM IWO IWN IWP IWS IJJ IJK IJT IJS SLYV SLYG SPMD SPSM VB VBR VBK
COST WMT TGT KR
BRK-B BRK-A
NVO AZN NVS SNY GSK UL BTI SAP ASML TSM SONY TM TM-DUP RIO BHP VALE PDD BABA MELI SE NU IBN HDB INFY HSBC RY TD BMO BNS CM
GRAB SE CP ATI
CRH FERG RELX WDS
AEM GOLD AU WPM FNV PAAS CDE HL
U UBER DASH ABNB
TOST CAVA WING SHAK BROS CAKE TXRH EAT WEN PZZA
CROX DECK LULU NKE ADDYY
CELH MNST KDP KO PEP
SMCI DELL APP PLTR
HIMS OWL
RKLB ASTS LUNR JOBY ACHR
IONQ RGTI QUBT QBTS
SOUN AI PATH SNOW DDOG
MSTR COIN HOOD CLSK MARA RIOT HUT IREN CIFR WULF CORZ BTDR BITF
NU MELI SE XP TIGR BILI TME NTES BIDU JD PDD BABA
TSM ASML 000660.KS 005930.KS
SPY QQQ IWM SMH
VST CEG NRG PWR VRT ETN GEV HUBB AME
AXON TDG HEI TDG
CRWD PANW FTNT ZS S NET DDOG
LLY NVO VKTX GPCR MDGL INSM
ISRG BSX SYK DXCM PODD
KLAC LRCX AMAT
MU 000660.KS
AVGO NVDA TSM
META AMZN GOOG MSFT AAPL
TSLA RIVN LCID NIO XPEV LI
F GM TM HMC
CAT DE PCAR CMI
UNP CSX NSC
BA RTX LMT GD NOC
XOM CVX COP
NEE CEG VST
PLD EQIX AMT
JPM GS MS
UNH LLY
COST WMT
HD LOW
NKE LULU
MCD SBUX
DIS NFLX
V MA
WFC BAC
PFE MRK
ABBV JNJ
KO PEP
PG CL
T VZ TMUS
INTC AMD
QCOM AVGO
ORCL CRM NOW
ADBE INTU
IBM ACN
CSCO ANET
AMAT LRCX
VST CEG NRG HUBB AME HEI CW FIX STRL ROAD PRIM MYRG ACM J EME APG MTZ DY FLR TTEK WWD ITT IR NDSN DOV XYL PNR ROP AME FTV TDY TXT HII LDOS BAESY GD
WING SHAK BROS CAKE TXRH EAT WEN PZZA BJ SFM CASY ELF COTY ELF IPAR
CROX BIRK ONON ASICS ADDYY NKE SKX WWW COLM PVH RL TPR CPRI HBI UAA
HIMS OWL RKLB ASTS LUNR JOBY ACHR IONQ RGTI QUBT QBTS SOUN AI PATH
MSTR CLSK MARA RIOT HUT IREN CIFR WULF CORZ BTDR BITF COIN HOOD
GRAB CP ATI CRH FERG RELX AEM GOLD AU WPM FNV PAAS CDE HL
TOST CAVA TXG BEAM CRSP NTLA TWST EXAS NTRA GH SDGR TEM OSCR UNH
UPST AFRM LC SOFI HOOD COIN PYPL XYZ V MA
SNOW DDOG NET CRWD PANW ZS FTNT MDB ESTC CFLT HUBS TEAM WDAY NOW
APP PLTR SMCI DELL ANET AVGO
CELH MNST KDP KO PEP STZ SAM TAP BF-B
FIVE OLLI DG DLTR BBY BBWI RH WSM TSCO POOL
CHWY PETS FRPT WING CMG
RIVN LCID NIO XPEV LI F GM HMC TM
U RBLX EA TTWO SPOT NFLX DIS PARA WBD LYV
DKNG PENN WYNN LVS MGM CZR BYD
FICO ANSS ADSK ACN IBM CTSH EPAM GLOB ACN
PAYC PCTY WDAY TEAM NOW CRM
OKTA CYBR S CRWD
TOST BILL GPN FIS FI PYPL
TWLO BAND ZM TEAM
DUOL CHGG COUR
LEVI PVH RL
DECK LULU NKE ONON
ARM TSM ASML AMAT LRCX KLAC
MPWR AVGO NXPI MCHP ON ADI TXN QCOM
WDC STX NTAP PSTG DELL HPE
ANET CSCO MSI JNPR FFIV
GLW TEL APH KEYS
FSLR ENPH RUN SEDG CSIQ JKS NXT
PLUG BE BLNK CHPT EVGO
ALB SQM LTHM
NUE STLD RS CLF X
FCX SCCO TECK VALE RIO BHP
NEM GOLD AEM WPM FNV
CTRA OVV PR AR APA MRO DVN FANG
TRGP WMB KMI OKE LNG
CEG VST NRG AES PCG SRE NEE
VRT ETN GEV PWR HUBB AME
AXON TDG HEI CW
CRH MLM VMC
SHW PPG ECL
LIN APD AIR
WELL VTR DOC PEAK
IRM SBAC AMT CCI
PLD EQIX DLR
SPG KIM REG
O NNN ADC
AVB EQR ESS UDR MAA CPT
PSA EXR CUBE
WY PCH RYN
JPM BAC WFC C USB PNC TFC COF
GS MS SCHW BLK BX KKR APO
V MA AXP DFS SYF
PGR ALL TRV CB CINF WRB
MET PRU AFL AIG
MMC AON AJG BRO
ICE CME NDAQ MSCI MCO SPGI
TROW BEN IVZ AMP RJF NTRS
BK STT FITB KEY RF HBAN CFG
ALLY HOOD SOFI COIN
UNH ELV CI HUM CNC MOH
HCA UHS THC
CVS WBA MCK CAH COR
JNJ LLY ABBV MRK PFE BMY AMGN GILD
VRTX REGN ZTS ALNY INCY EXEL BMRN NBIX UTHR
ISRG BSX SYK MDT EW IDXX DXCM PODD ALGN
TMO DHR A WAT MTD IQV ICLR MEDP
BDX BAX HOLX ZBH RMD STE TFX
ABT KVUE EL ULTA
COST WMT TGT KR CASY SFM BJ
HD LOW TSCO POOL BBY
NKE LULU DECK CROX SKX
MCD SBUX YUM CMG DASH DPZ WING SHAK
DIS NFLX PARA WBD CMCSA
T VZ TMUS CHTR
PG CL KMB CHD CLX
KO PEP MNST KDP CELH
PM MO BTI
NEE DUK SO AEP D EXC XEL
XOM CVX COP SLB EOG
CAT DE BA HON UNP
MSFT AAPL NVDA AMZN GOOG META
IWM QQQ SPY SMH SOXX
IBIT FBTC ARKB BITO GBTC ETHE
XLC IGV SKYY CIBR BUG
XHB ITB XME XOP KRE
EFA EEM VEA VWO IEFA IEMG
GLD IAU SLV GDX GDXJ
TLT IEF BND AGG LQD HYG
USO UNG DBA DBC
TAN ICLN QCLN LIT REMX COPX
BOTZ ROBO QTUM HACK
DIA MDY IJR IWM IWO IWN
VOO VTI VUG VTV VGT
RSP MOAT QUAL MTUM VLUE USMV
JEPI JEPQ QYLD SCHD DGRO
ARKK ARKW ARKG ARKQ ARKF
KWEB FXI MCHI INDA EWZ EWJ
PPLT PLTM SIVR PALL
SGOV BIL SHV FLOT
UPRO TQQQ SOXL SPXL TNA
SQQQ
HIMS DUOL TOST CAVA
RKLB ASTS JOBY
IONQ RGTI
MSTR
VKTX GPCR MDGL INSM CYTK BBIO RARE FOLD ACLX
S MRVL ARM
ANET AVGO
APP PLTR
COIN HOOD
CRWD PANW
LLY NVO
VST CEG
GEV VRT
AXON TDG
SMCI DELL
FIX STRL ROAD PRIM MYRG ACM EME APG MTZ DY FLR TTEK WWD ITT NDSN
BJ SFM CASY ELF COTY IPAR FIVE OLLI BBWI RH WSM
BIRK ONON SKX WWW COLM PVH TPR CPRI HBI UAA LEVI
OWL LUNR ACHR QUBT QBTS PATH ESTC CFLT CYBR BILL BAND CHGG COUR
CLSK MARA RIOT HUT IREN CIFR WULF CORZ BTDR BITF
CP ATI FERG RELX GOLD AU PAAS CDE HL
TXG BEAM CRSP NTLA TWST EXAS NTRA GH SDGR TEM OSCR UHS THC WBA
UPST AFRM LC GLOB PAYC PCTY
PSTG JNPR RUN SEDG CSIQ JKS NXT PLUG BLNK CHPT EVGO SQM LTHM CLF SCCO TECK
NNN ADC CUBE PCH RYN CINF WRB UHS ICLR MEDP IPAR SAM TAP BF-B PETS FRPT PENN WYNN LVS MGM CZR BYD
FBTC ARKB BUG IEMG VGK EWT EWY EWH EWS EWA EWC EWG EWI EWP EWU ASHR SCHE SPEM VYMI SCHZ SPHY SJNK QCLN PBW FAN SMOG GRID WCLD IRBO IAI IYF IYG IYJ IYC IYK IHI GNOM IDNA IWB IVE IVW SPHQ SPLG IVV VFH VHT VIS VCR VDC VDE VAW VNQ VPU VIG VYM SCHG SCHV SCHX DGRW XYLD RYLD DIV SCHG VXUS IEFA
BNDX MUB VCIT VCSH GOVT TIP BNO GSG SMOG
TNA UWM QLD SSO SPXL
IWO IWN IWP IWS IJJ IJK IJT IJS SLYV SLYG SPMD SPSM VBR VBK
BMO BNS CM GRAB
CYTK BBIO RARE FOLD ACLX GPCR MDGL INSM
CPRT ODFL SAIA XPO JBHT EXPD CHRW LSTR KNX WAB TRMB ZBRA NWS GDDY DOCU ZI ZETA PEGA MANH GWRE MNDY IOT GTLB GT FND DRI BALL
BP SHEL TTE EQNR ENB TRP SU CNQ NGG DEO BUD ASX WIT KHC SJM HRL CPB CAG MKC TSN LW
WEAT CORN SOYB BITI BITX CONY NVDY SVOL XRT XSD XTN XAR ITA PPA MOO
OKLO SMR RKT OPEN HOUS COMP UWMC NOK ERIC
`

function uniqueTickers(src: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const part of src.split(/[\s,]+/)) {
    const t = part
      .trim()
      .toUpperCase()
      .replace(/-DUP$/g, "")
      .replace(/-SKIP$/g, "");
    if (!t || seen.has(t)) continue;
    if (!/^[A-Z0-9.-]{1,12}$/.test(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

export const SCAN_UNIVERSE: string[] = uniqueTickers(RAW);
